name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        shell: bash
        run: |
          # Install Foundry
          curl -L https://foundry.paradigm.xyz | bash
          # Source the bashrc to load PATH changes
          source ~/.bashrc
          # Now call foundryup
          foundryup

      - name: Run tests
        run: forge test
