name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        shell: bash
        run: |
          # Install Foundry
          curl -L https://foundry.paradigm.xyz | bash
          # Now call foundryup
          $HOME/.foundry/bin/foundryup

      - name: Run tests
        run: $HOME/.foundry/bin/forge test
